### ISSUE TITLE
INQUIRY: Is this project still alive?

### ISSUE THREAD

**Issue by Sethadon** [FireSiku/LUI-V4#1]
Last week (24-APR-2018) Blizz released Battle for Azeroth (BfA) BETA, which got me curious about whether or not this brilliant UI will still be functional come the new expansion - in August 2018? - It is hands down the best looking UI, and it would be a shame if this work was discontinued.

Please advise.

Thanks. 👍

**Comment by Sethadon** [comment]
Thank you for your quick response. If you need someone to help test things out in Beta, just say the word. ;)

**Comment by Sethadon** [comment]
QUESTION: I downloaded the latest version of LUI4 [here](https://wow.curseforge.com/projects/lui-v4/files/2561858/download) and received 51 different lua errors upon logging in to BfA BETA. Is this project not yet being modified for BfA at this time?

IMO: It would be quite counter productive to get this addon working with Legion v7.3.5, when BfA 8.x is just around the corner (projected to be released in August this year).

**Comment by FireSiku** [comment]
yeah, I haven't yet fixed all the issues with BfA yet, but I am definitely not going to work on make it working with Legion at all (sadly). There are things are going with me, but Ive been getting more and more into the groove of working on WoW stuff, since I havent touched the game much since my guild "hibernated".
